/*
 * This source file was generated by the Gradle 'init' task
 */
package mytabungan;

import java.sql.SQLException;

import javafx.application.Application;
import javafx.stage.Stage;
import mytabungan.scenes.LoginScene;
import mytabungan.*;
import mytabungan.database.DBIniatializer;
import mytabungan.database.DatabaseConfig;

public class App  extends Application{

    @Override
    public void start(Stage primaryStage) {
        // DBIniatializer.init();

        LoginScene loginScene = new LoginScene(primaryStage);
        primaryStage.setScene(loginScene.getLogin(primaryStage));

        primaryStage.setTitle("Tabungin");
        primaryStage.show();
    }
    public static void main(String[] args) {
        // try {
        //     DatabaseConfig.connect();
        //     System.out.println("Koneksi berhasil!");
        // } catch (SQLException e) {
        //     System.out.println("Koneksi gagal!");

        //     e.printStackTrace();.\gradlew run
        // }
        launch(args);
    }
}
